name: Deploy website via SSH

on:
  push:
    branches: [website]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@master

      # Copying files to server via SSH
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "index.html,robots.txt,sitemap.xml,favicon.svg,apple-touch-icon.png,manifest.json"
          target: "${{ secrets.REMOTE_WEBSITE_DIR }}"

      # Restart NGINX after deploy
      - name: Restart NGINX
        uses: garygrossgarten/github-action-ssh@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          command: sudo nginx -t && sudo systemctl restart nginx
